"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--e&9_r!5&-t3+%d9ac5=3bmulsp47y!5woqah@-x-2+-8bd@6+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#     "handlers": {
#         "console": {
#             "level": "DEBUG",
#             "class": "logging.StreamHandler",
#         },
#         "file": {
#             "level": "DEBUG",
#             "class": "logging.FileHandler",
#             "filename": "debug.log",  # 로그가 저장될 파일 이름
#         },
#     },
#     "loggers": {
#         "django": {
#             "handlers": ["console", "file"],  # 콘솔과 파일 모두에 로그 출력
#             "level": "DEBUG",
#         },
#         "__main__": {
#             "handlers": ["console", "file"],  # 콘솔과 파일 모두에 로그 출력
#             "level": "DEBUG",
#         },
#     },
# }
# Application definition

INSTALLED_APPS = [
    "daphne",
    "channels",
    'studydashboard',
    'quizarchive',
    'studyarchive',
    'accounts',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.admin',
    'corsheaders',  # CORS 미들웨어 추가
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS 미들웨어 추가
    'django.middleware.common.CommonMiddleware',  # CommonMiddleware는 CORS 미들웨어 뒤에 위치해야 함
]

# 모든 도메인에서 접근 허용 (특정 도메인으로 제한할 수 있음)
CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            str(BASE_DIR / 'common_templates'),  # 경로를 문자열로 변환
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'

ASGI_APPLICATION = "myproject.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],  # Redis 서버 주소와 포트
        },
    },
}
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# # 데이터베이스 연결 URL
# DATABASE_URL = os.getenv("DATABASE_URL", "postgresql://postgres:postgres@211.184.186.6:5432/postgres")

# # 데이터베이스 URL 파싱
# url = urlparse(DATABASE_URL)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': url.path[1:],  # Remove leading slash
#         'USER': url.username,
#         'PASSWORD': url.password,
#         'HOST': url.hostname,
#         'PORT': url.port,
#         'OPTIONS': {
#             'sslmode': 'disable',  # SSL 비활성화
#         }
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  # PostgreSQL 엔진 사용
        'NAME': 'younib',                          # 생성한 데이터베이스 이름
        'USER': 'younib',                          # 데이터베이스 사용자 이름
        'PASSWORD': 'younib',                      # 해당 사용자의 비밀번호
        'HOST': '127.0.0.1',                       # 로컬 PostgreSQL 서버 주소
        'PORT': '5432',                            # PostgreSQL 기본 포트
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Static files URL
STATIC_URL = '/static/'

# Collectstatic 명령으로 정적 파일이 모이는 최종 디렉토리
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Django가 정적 파일을 검색할 추가 디렉토리
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # 프로젝트의 static 디렉토리를 추가
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 로그인 후 리다이렉트할 URL
LOGIN_REDIRECT_URL = '/'  # 로그인 성공 시 이동할 경로 (홈 페이지)
LOGOUT_REDIRECT_URL = '/'  # 로그아웃 성공 시 이동할 경로

# 로그인 URL (사용자가 로그인해야 접근 가능한 페이지에 요청 시 리다이렉트할 URL)
LOGIN_URL = '/accounts/login_register/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AUTH_USER_MODEL = 'accounts.CustomUser'

