# Generated by Django 5.1.4 on 2024-12-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyarchive', '0003_coursematerial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
